export { Home } from './Home'
export { About } from './About'
export { Contact } from './Contact'
export { BBFAdminPage } from './BBFPage'
export { Departament } from './Departament'
export { DepartamentItem } from './DepartamentItem'
export { DepartamentItems } from './DepartamentItems'
